# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eprotobuf.proto\"~\n\x05\x66ield\x12\x12\n\nsnake_case\x18\x01 \x01(\t\x12\x14\n\x0c\x66ield_number\x18\x03 \x01(\r\x12\x13\n\x0b\x66ield_label\x18\x04 \x01(\r\x12\x12\n\nfield_type\x18\x05 \x01(\r\x12\x0e\n\x06import\x18\x06 \x01(\t\x12\x12\n\ncamel_case\x18\n \x01(\t\"(\n\nenum_field\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\r\"?\n\x04\x65num\x12\x11\n\tenum_name\x18\x01 \x01(\t\x12$\n\x0f\x65num_field_list\x18\x02 \x03(\x0b\x32\x0b.enum_field\"u\n\x07message\x12\x14\n\x0cmessage_name\x18\x01 \x01(\t\x12\x1a\n\nfield_list\x18\x02 \x03(\x0b\x32\x06.field\x12\x1e\n\x0cmessage_list\x18\x03 \x03(\x0b\x32\x08.message\x12\x18\n\tenum_list\x18\x04 \x03(\x0b\x32\x05.enum\"3\n\x10proto_definition\x12\x0b\n\x03idk\x18\t \x01(\r\x12\x12\n\nproto_type\x18\x0b \x01(\t\"\xcb\x01\n\x11protobuf_template\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x0cpackage_name\x18\x02 \x01(\t\x12\x15\n\rimport_protos\x18\x03 \x03(\t\x12\x1e\n\x0cmessage_list\x18\x04 \x03(\x0b\x32\x08.message\x12\x18\n\tenum_list\x18\x05 \x03(\x0b\x32\x05.enum\x12+\n\x10proto_definition\x18\x08 \x01(\x0b\x32\x11.proto_definition\x12\x14\n\x0cproto_syntax\x18\x0c \x01(\t\"0\n\x08protobuf\x12$\n\x08protobuf\x18\x01 \x01(\x0b\x32\x12.protobuf_templateb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_FIELD']._serialized_start=18
  _globals['_FIELD']._serialized_end=144
  _globals['_ENUM_FIELD']._serialized_start=146
  _globals['_ENUM_FIELD']._serialized_end=186
  _globals['_ENUM']._serialized_start=188
  _globals['_ENUM']._serialized_end=251
  _globals['_MESSAGE']._serialized_start=253
  _globals['_MESSAGE']._serialized_end=370
  _globals['_PROTO_DEFINITION']._serialized_start=372
  _globals['_PROTO_DEFINITION']._serialized_end=423
  _globals['_PROTOBUF_TEMPLATE']._serialized_start=426
  _globals['_PROTOBUF_TEMPLATE']._serialized_end=629
  _globals['_PROTOBUF']._serialized_start=631
  _globals['_PROTOBUF']._serialized_end=679
# @@protoc_insertion_point(module_scope)
